server:
  port: 8095

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/users?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=Africa/Luanda
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      dll-auto: none
      format_sql: true



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    preferIpAddress: true

openapi:
  service:
    title: test-service doc
    version: 1.0.0
    url: http://localhost:8888 #api gateway url
springdoc:
  api-docs:
    path: user-service/v3/api-docs
  swagger-ui:
    path: user-service/swagger-ui.html